### ISSUE TITLE
RP2 Port: 'module' object has no attribute 'disp_drv_t'

### ISSUE THREAD

**Issue by robin7331** [lvgl/lv_binding_micropython#303]
Hey there! I'm trying to get my **RP2 Pico** working with LVGL but I had no luck so far.
Maybe I'm missing something obvious?

I am building `lv_micropython` using this GitHub Action:

```
on:
  push:
    branches:
      - main

jobs:
  local-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Checkout LVGL
        uses: actions/checkout@v4
        with:
          repository: lvgl/lv_micropython
          ref: "b1301ee8359454fd8b68b4063874e5034b4d9fe5" # Last commit on master
          path: "./lv_micropython"
          submodules: true
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git python3 -y
      - name: Init Submodules
        run: |
          cd "$GITHUB_WORKSPACE/lv_micropython"
          git submodule update --init --recursive lib/lv_bindings
      - name: Make RP2 / PICO Submodules
        run: |
          cd "$GITHUB_WORKSPACE/lv_micropython"
          make -j$(nproc) -C ports/rp2 BOARD=PICO USER_C_MODULES=../../lib/lv_bindings/bindings.cmake submodules
      - name: Make mpy-cross
        run: |
          cd "$GITHUB_WORKSPACE/lv_micropython"
          make -j$(nproc) -C mpy-cross
      - name: Make Firmware
        run: |
          cd "$GITHUB_WORKSPACE/lv_micropython"
          make -j$(nproc) -C ports/rp2 BOARD=PICO USER_C_MODULES=../../lib/lv_bindings/bindings.cmake
          mv $GITHUB_WORKSPACE/lv_micropython/ports/rp2/build-PICO/firmware.uf2 $GITHUB_WORKSPACE/firmware.uf2
```

The build works. Once I flash the UF2 to my Pico I can for example successfully import and init lvgl via 

```
import lvgl as lv
lv.init()
```

but once I try to register a display driver I get the `AttributeError: 'module' object has no attribute 'disp_drv_t'` error.

```
# Register the display driver
disp_drv = lv.disp_drv_t()      # This line fails
disp_drv.init()
disp_drv.flush_cb = lvgl_flush_cb
disp_drv.hor_res = DISPLAY_WIDTH
disp_drv.ver_res = DISPLAY_HEIGHT
disp_drv.register()
```

Does anybody know what the issue is here? 
Thanks in advance!
